Entity/User/User.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *   (c) CERT UNLP <support@cert.unlp.edu.ar>
 *  This source file is subject to the GPL v3.0 license that is bundled
 *  with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Entity\User;

use CertUnlp\NgenBundle\Entity\Communication\Contact\Contact;
use CertUnlp\NgenBundle\Entity\Communication\Contact\ContactEmail;
use CertUnlp\NgenBundle\Entity\Communication\Contact\ContactPhone;
use CertUnlp\NgenBundle\Entity\Communication\Contact\ContactTelegram;
use CertUnlp\NgenBundle\Entity\Incident\Incident;
use CertUnlp\NgenBundle\Model\EntityApiFrontendInterface;
use CertUnlp\NgenBundle\Model\EntityApiInterface;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\GroupInterface;
use FOS\UserBundle\Model\User as BaseUser;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as JMS;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * User
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="CertUnlp\NgenBundle\Repository\User\UserRepository")
 * @UniqueEntity(
 *     fields={"username"},
 *     message="This username is already in use."
 * )
 * @UniqueEntity(
 *     fields={"email"},
 *     message="This email is already in use."
 * )
 * @ORM\HasLifecycleCallbacks
 * @JMS\ExclusionPolicy("all")
 */
class User extends BaseUser implements EntityApiFrontendInterface
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @var string
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    protected $username;

    /**
     * @var string
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    protected $email;

    /**
     * @var bool
     * @JMS\Expose
     * @JMS\SerializedName("active")
     * @JMS\Groups({"read","write"})
     */
    protected $enabled;
    /**
     * @var DateTime|null
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    protected $lastLogin;

    /**
     * @var GroupInterface[]|Collection
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    protected $groups;

    /**
     * @var array
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    protected $roles;
    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"firstname","lastname"}, separator="_")
     * @ORM\Column(name="slug", type="string", length=100,nullable=true)
     * */
    protected $slug;
    /**
     * @ORM\Column(name="api_key", type="string", length=255, nullable=true)
     */
    private $apiKey;
    /**
     * @var bool
     */
    private $generate_api_key=false;
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50)
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    private $firstname = '';
    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=50)
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    private $lastname = '';
    /**
     * @var DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @JMS\Expose
     * @JMS\Groups({"read"})
     */
    private $createdAt;
    /**
     * @var DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     * @JMS\Expose
     * @JMS\Groups({"read"})
     */
    private $updatedAt;
    /**
     * @ORM\OneToMany(targetEntity="CertUnlp\NgenBundle\Entity\Incident\Incident",mappedBy="reporter",fetch="EXTRA_LAZY")
     */
    private $incidents;
    /**
     * @ORM\OneToMany(targetEntity="CertUnlp\NgenBundle\Entity\Incident\Incident",mappedBy="assigned",fetch="EXTRA_LAZY")
     */
    private $assignedIncidents;
    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="CertUnlp\NgenBundle\Entity\Communication\Contact\Contact",mappedBy="user",cascade={"persist"},orphanRemoval=true)
     * @JMS\Expose()
     * @JMS\Groups({"read","write"})
     */
    private $contacts;
    /**
     * @var User|null
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\User\User")
     * @Gedmo\Blameable(on="create")
     */
    private $createdBy;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
        $this->incidents = new ArrayCollection();
        $this->assignedIncidents = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    /**
     * @return bool
     */
    public function isGenerateApiKey(): bool
    {
        return $this->generate_api_key;
    }

    /**
     * @param bool $generate_api_key
     * @return User
     */
    public function setGenerateApiKey(bool $generate_api_key): User
    {
        $this->generate_api_key = $generate_api_key;
        return $this;
    }

    /**
     * @return string
     */
    public function getIcon(): string
    {
        return 'users';
    }

    /**
     * @return string
     */
    public function getColor(): string
    {
        return 'info';
    }

    /**
     * Get emails
     *
     * @return string
     */
    public function getEmailsAsString(): ?string
    {
        return implode(',', $this->getEmails());
    }

    /**
     * Get emails
     *
     * @return array
     */
    public function getEmails(): array
    {
        $array_mails = $this->getContacts()->map(static function (Contact $value) {
            return $value->getEmail();
        });
        return array_merge($array_mails->toArray(), [$this->getEmail()]);
    }

    /**
     * @param int|null $priorityCode
     * @return Collection
     */
    public function getContacts(int $priorityCode = null): Collection
    {
        if ($priorityCode !== null) {
            return $this->contacts->filter(static function (Contact $contact) use ($priorityCode) {
                return $contact->getContactCase()->getLevel() >= $priorityCode;
            });
        }

        return $this->contacts;
    }

    /**
     * Get emails
     *
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->isEnabled();
    }

    /**
     * @return Collection|Incident[]|null
     */
    public function getAssignedIncidents(): ?Collection
    {
        return $this->assignedIncidents;
    }

    /**
     * @param Collection|Incident[] $assignedIncidents
     * @return User
     */
    public function setAssignedIncidents(Collection $assignedIncidents): User
    {
        $this->assignedIncidents = $assignedIncidents;
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return DateTime
     */
    public function getUpdatedAt(): DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Set updatedAt
     *
     * @param DateTime $updatedAt
     * @return User
     */
    public function setUpdatedAt(DateTime $updatedAt): User
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function timestampsUpdate(): void
    {
        $this->setUpdatedAt(new DateTime('now'));

        if ($this->getCreatedAt() == null) {
            $this->setCreatedAt(new DateTime('now'));
        }
    }

    /**
     * Get createdAt
     *
     * @return DateTime
     */
    public function getCreatedAt(): ?DateTime
    {
        return $this->createdAt;
    }

    /**
     * Set createdAt
     *
     * @param DateTime $createdAt
     * @return User
     */
    public function setCreatedAt(DateTime $createdAt): User
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Add incidents
     *
     * @param Incident $incidents
     * @return User
     */
    public function addIncident(Incident $incidents): User
    {
        $this->incidents[] = $incidents;

        return $this;
    }

    /**
     * @return Collection| Incident[]
     */
    public function getIncidents(): Collection
    {
        return $this->incidents;
    }

    public function __toString(): string
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getFirstname(): string
    {
        return $this->firstname;
    }

    /**
     * Set name
     *
     * @param string $firstname
     * @return User
     */
    public function setFirstname(string $firstname): User
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string
     */
    public function getLastname(): string
    {
        return $this->lastname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     * @return User
     */
    public function setLastname(string $lastname): User
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }

    /**
     * Get name
     *
     * @return string
     * @JMS\VirtualProperty()
     * @JMS\Expose()
     *
     */
    public function getFullName(): string
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }

    /**
     * Get apiKey
     *
     * @return string
     */
    public function getApiKey(): string
    {
        return $this->apiKey;
    }

    /**
     * Set apiKey
     *
     * @param string $apiKey
     * @return User
     */
    public function setApiKey(string $apiKey): User
    {
        $this->apiKey = $apiKey;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug(): string
    {
        return $this->slug;
    }

    /**
     * Set slug
     *
     * @param string $slug

Controller/Frontend/Constituency/NetworkAdminFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 * 
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 * 
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of NetworkAdminFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Constituency;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkAdmin;
use CertUnlp\NgenBundle\Form\Constituency\NetworkAdminType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NetworkAdminFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_network_admin_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->homeEntity($request, $elastica_finder_network_admin);
    }


    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin/Frontend:home.html.twig")
     * @Route("search", name="cert_unlp_ngen_network_search_network_admin")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function searchNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->searchEntity($request, $elastica_finder_network_admin);
    }

    /**
     * @Route("search/autocomplete", name="cert_unlp_ngen_network_admin_search_autocomplete")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return JsonResponse
     */
    public function searchAutocompleteNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): JsonResponse
    {
        return $this->searchAutocompleteEntity($request, $elastica_finder_network_admin);

    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_network_new_network_admin")
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function newNetworkAdminAction(NetworkAdminType $admin_type): array
    {
        return $this->newEntity($admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_network_edit_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/edit", name="cert_unlp_ngen_network_edit_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function editNetworkAdminAction(NetworkAdmin $network_admin, NetworkAdminType $admin_type): array
    {
        return $this->editEntity($network_admin, $admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_network_detail_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/detail", name="cert_unlp_ngen_network_detail_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @return array
     */
    public function detailNetworkAdminAction(NetworkAdmin $network_admin): array
    {
        return $this->detailEntity($network_admin);
    }

}

Controller/Frontend/Constituency/NetworkEntityFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of NetworkEntityFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Constituency;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkEntity;
use CertUnlp\NgenBundle\Form\Constituency\NetworkEntityType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NetworkEntityFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_network_network_entity_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): array
    {
        return $this->homeEntity($request, $elastica_finder_network_entity);
    }

    /**
     * @Route("search/autocomplete", name="cert_unlp_ngen_network_entity_search_autocomplete")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return JsonResponse
     */
    public function searchAutocompleteNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): JsonResponse
    {
        return $this->searchAutocompleteEntity($request, $elastica_finder_network_entity);

    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/home.html.twig")
     * @Route("search", name="cert_unlp_ngen_network_entity_search")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return array
     */
    public function searchNetworkEntityAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): array
    {
        return $this->searchEntity($request, $elastica_finder_network_entity);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_network_entity_new")
     * @param NetworkEntityType $entity_type
     * @return array
     */
    public function newNetworkEntityAction(NetworkEntityType $entity_type): array
    {
        return $this->newEntity($entity_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_network_entity_edit_id",requirements={"id"="\d+"})
     * @Route("{slug}/edit", name="cert_unlp_ngen_network_entity_edit_slug")
     * @param NetworkEntity $network_entity
     * @param NetworkEntityType $entity_type
     * @return array
     */
    public function editNetworkEntityAction(NetworkEntity $network_entity, NetworkEntityType $entity_type): array
    {
        return $this->editEntity($network_entity, $entity_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_network_entity_detail_id",requirements={"id"="\d+"})
     * @Route("{slug}/detail", name="cert_unlp_ngen_network_entity_detail_slug")
     * @param NetworkEntity $network_entity
     * @return array
     */
    public function detailNetworkEntityAction(NetworkEntity $network_entity): array
    {
        return $this->detailEntity($network_entity);
    }

}

Resources/views/User/Frontend/changePasswd.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}

{% extends 'CertUnlpNgenBundle::frontend.html.twig' %}

{% block content_header %}
    <h1 class="page-header">{{ icon('key fa-fw') }}{{ 'Change password'|trans }}</h1>
{% endblock %}
{% block content_body %}
    {% if (form is not null) %}
        {{ form_errors(form, { 'global_errors': true }) }}
        {{ form(form, {'attr': {'id': 'add_update_form'},'style': 'horizontal', 'col_size': 'sm' }) }}
    {% endif %}
{% endblock %}

Resources/views/User/Frontend/frontend.html.twig
{# 
 This file is part of the Ngen - CSIRT User Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}
{% extends 'CertUnlpNgenBundle::frontend.html.twig' %}

{% block title %}{{ 'Users'|trans }}{% endblock %}
    {% block content_header %}
        <h1 class="h3 mb-0 text-gray-800">{{ icon('users fa-fw') }} {{ 'Users'|trans }}</h1>
        <a href="{{ path('cert_unlp_ngen_user_new_user') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus-circle fa-sm text-white-50"></i>{{ 'add User'|trans }} </a>
   {% endblock %}


{% block sideBar_search_path %}{{ path('cert_unlp_ngen_user_search_user') }}{% endblock %}

{% block content_body %}
    {% include 'CertUnlpNgenBundle:User:Frontend/list/userList.html.twig' with {'users': objects} %}
{% endblock %}


{% block javascripts %}
    {{ parent() }}

    {% javascripts
        '@CertUnlpNgenBundle/Resources/public/js/user/User.js'
        '@CertUnlpNgenBundle/Resources/public/js/user/UserApi.js' %}
        <script src="{{ asset('js/jquery.collection.js') }}"></script>
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script>
        var user = new User();
        var user_api = new UserApi("{{ path("api_get") }}", "{{ app.user.apiKey }}");
    </script>
{% endblock %}

Resources/views/User/Frontend/home.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}
{% extends 'CertUnlpNgenBundle::User/Frontend/frontend.html.twig' %}

{% block content_body %}
    {% include 'CertUnlpNgenBundle:User:Frontend/list/userList.html.twig' with {'users': objects} %}
{% endblock %}

Resources/views/User/Frontend/login.html.twig
{#
This file is part of the Ngen - CSIRT Incident Report System.
z
(c) CERT UNLP <support@cert.unlp.edu.ar>

This source file is subject to the GPL v3.0 license that is bundled
with this source code in the file LICENSE.
#}

{% extends 'CertUnlpNgenBundle::base.html.twig' %}

{% block title %}{{ 'User Login'|trans }}{% endblock %}
{% block id 'login' %}
{% block body %}

    <style>
        .login-image-ngen {
            background: url({{ asset('bundles/certunlpngen/images/ngen01.svg') }});
            background-position: center;
            background-size: contain;
        }
    </style>
    <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">

                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block login-image-ngen"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">{{ 'Welcome Back!'|trans }}</h1>
                                </div>
                                <form role="form" class="user" _lpchecked="1"
                                      action="{{ path('fos_user_security_check') }}" method="post">
                                    <input type="hidden" name="_csrf_token"
                                           value="{{ csrf_token('authenticate') }}"/>
                                    {% if error %}
                                        <div class="alert-danger col-md-3 offset-10">{{ error.message }}</div>
                                    {% endif %}
                                    <div class="form-group">
                                        <input value="{{ last_username }}" type="text" id="username"
                                               name="_username"
                                               class="form-control form-control-user" placeholder="Username"
                                               required="" autofocus=""
                                               autocomplete="off">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" id="password" name="_password"
                                               class="form-control form-control-user"
                                               placeholder="Password" required="" autocomplete="off">
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox small">
                                            <input type="checkbox" class="custom-control-input" name="_remember_me"
                                                   id="remember_me"
                                                   checked>
                                            <label class="custom-control-label"
                                                   for="remember_me">{{ 'Remember me'|trans }}</label>
                                        </div>
                                    </div>
                                    <div class="form-group">

                                        <input class="btn btn-primary btn-user btn-block" type="submit"
                                               name="login"
                                               value="{{ "Login" | trans }}"/>
                                    </div>
                                </form>

                                <hr>
                                <div class="text-center">
                                    <a class="small pull-right btn btn-link"
                                       href="{{ path('fos_user_resetting_request') }}">
                                        {{ 'Forgot password?'|trans }}
                                    </a>
                                </div>
                                <div class="text-center">
                                    <a class="small pull-left btn btn-link"
                                       href="{{ path('fos_user_registration_register') }}">{{ 'Register'|trans }}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Resources/views/User/Frontend/userDetail.html.twig
{# createdAt
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}

{% extends 'CertUnlpNgenBundle::User/Frontend/frontend.html.twig' %}
{% import '@CertUnlpNgen/Frontend/detailMacros.html.twig' as print %}
{% block content_header %}
    <h1 class="h3 mb-0 text-gray-800">
        {{ icon(object.icon ~' fa-fw text-'~object.color) }}
        {{ object }}
        {{ print.colorboxbutton('primary','id-card',object.id,'#') }}
        {{ print.statusbox(object) }}
        {{ print.colordropbox('primary','arrow-circle-down','incidents '~object.incidents.count,path('cert_unlp_ngen_internal_incident_search_incident',{'term':'reporter: "'~object~'"'}),'','d-inline') }}
        {{ print.colordropbox('primary','arrow-circle-down','assigned incidents '~object.assignedIncidents.count,path('cert_unlp_ngen_internal_incident_search_incident',{'term':'assigned: "'~object~'"'}),'','d-inline') }}
        {{ print.colorbox('primary','edit','Edit',path('cert_unlp_ngen_user_edit_user',{'username': object.username})) }}
    </h1>
{% endblock %}
{% block content_body %}
    <div class="row">
        <div class="col-lg-6">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">{{ 'User Information'|trans }}</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tr>
                                <td class="">
                                    {{ "System Id"|trans }}
                                </td>
                                <td class="">
                                    {{ object.id }}
                                </td>
                            </tr>
                            <tr>
                                <td class="">
                                    {{ 'Userame'|trans }}
                                </td>
                                <td class="">
                                    {{ object.username }}
                                </td>
                            </tr>
                            <tr>
                                <td class="">
                                    {{ 'Name'|trans }}
                                </td>
                                <td class="">
                                    {{ object.fullName }}
                                </td>
                            </tr>
                            <tr>
                                <td class="">
                                    Last login{{ 'Forgot'|trans }}
                                </td>
                                <td class="">
                                    {{ object.lastLogin|date('Y-m-d') }}
                                </td>
                            </tr>
                            <tr>
                                <td class="">
                                    {{ 'Created at'|trans }}
                                </td>
                                <td class="">
                                    {{ object.createdAt|date('Y-m-d') }}
                                </td>
                            </tr>

                            <tr>
                                <td class="">
                                    {{ 'Last Update'|trans }}
                                </td>
                                <td class="">
                                    {{ object.updatedAt|date('Y-m-d') }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Resources/views/User/Frontend/userForm.html.twig
{#
This file is part of the Ngen - CSIRT Incident Report System.

(c) CERT UNLP <support@cert.unlp.edu.ar>

This source file is subject to the GPL v3.0 license that is bundled
with this source code in the file LICENSE.
#}

{% extends 'CertUnlpNgenBundle::User/Frontend/frontend.html.twig' %}
{% block content_header %}
    <h1 class="h3 mb-0 text-gray-800">{{ icon('plus-circle fa-fw') }}{{ 'add user'|trans }}</h1>
{% endblock %}
{% block content_body %}
    <div id="error">
    </div>
    {% if (form is not null) %}
        {% form_theme form
            'jquery.collection.html.twig'
            'CertUnlpNgenBundle:NetworkAdmin/Frontend:contacts.html.twig' %}
        {{ form(form, {'attr': {'role':'form','id': 'add_update_form'},'style': 'horizontal' ,'col_size': 'sm' }) }}
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    {% javascripts
        '@CertUnlpNgenBundle/Resources/public/js/user/UserForm.js' %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script>
        var user_form = new UserForm();
        $('.user-contacts').collection({
                drag_drop: false,
                allow_up: false,
                allow_down: false,
                allow_duplicate: false,
                fade_in: false,
                fade_out: false,
                add_at_the_end: true,
                init_with_n_elements: 0,
                add: '<a href="#" class="btn btn-info d-block"><span class="fa fa-plus "></span></a>',
            }
        );
    </script>
{% endblock %}