Entity/Incident/IncidentComment.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Entity\Incident;

use CertUnlp\NgenBundle\Entity\User\User;
use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Comment as BaseComment;
use FOS\CommentBundle\Entity\Thread;
use FOS\CommentBundle\Model\SignedCommentInterface;
use FOS\CommentBundle\Model\ThreadInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class IncidentComment extends BaseComment implements SignedCommentInterface
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * Thread of this comment
     *
     * @var Thread
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentCommentThread")
     */
    protected $thread;


    /**
     * Author of the comment
     *
     * @var User
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\User\User")
     */
    private $author = null;
    /**
     * @var boolean
     */
    private $notify_to_admin = false;

    /**
     * {@inheritDoc}
     */
    public function getAuthorName(): string
    {
        if (null === $this->getAuthor()) {
            return 'Anonymous';
        }

        return $this->getAuthor()->getUsername();
    }

    /**
     * @return User|UserInterface
     */
    public function getAuthor(): ?UserInterface
    {
        return $this->author;
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor(UserInterface $author): IncidentComment
    {
        $this->author = $author;
        return $this;
    }

    /**
     * Set thread
     *
     * @param ThreadInterface $thread
     * @return IncidentComment
     */
    public function setThread(ThreadInterface $thread = null): IncidentComment
    {
        $this->thread = $thread;

        return $this;
    }

    /**
     * @return bool
     */
    public function getNotifyToAdmin(): bool
    {
        return $this->notify_to_admin;
    }

    /**
     * @param $notify_to_admin
     * @return $this
     */
    public function setNotifyToAdmin(bool $notify_to_admin): IncidentComment
    {
        $this->notify_to_admin = $notify_to_admin;
        return $this;
    }


}

Controller/Frontend/Constituency/NetworkAdminFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 * 
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 * 
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of NetworkAdminFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Constituency;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkAdmin;
use CertUnlp\NgenBundle\Form\Constituency\NetworkAdminType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NetworkAdminFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_network_admin_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->homeEntity($request, $elastica_finder_network_admin);
    }


    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin/Frontend:home.html.twig")
     * @Route("search", name="cert_unlp_ngen_network_search_network_admin")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function searchNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->searchEntity($request, $elastica_finder_network_admin);
    }

    /**
     * @Route("search/autocomplete", name="cert_unlp_ngen_network_admin_search_autocomplete")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return JsonResponse
     */
    public function searchAutocompleteNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): JsonResponse
    {
        return $this->searchAutocompleteEntity($request, $elastica_finder_network_admin);

    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_network_new_network_admin")
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function newNetworkAdminAction(NetworkAdminType $admin_type): array
    {
        return $this->newEntity($admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_network_edit_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/edit", name="cert_unlp_ngen_network_edit_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function editNetworkAdminAction(NetworkAdmin $network_admin, NetworkAdminType $admin_type): array
    {
        return $this->editEntity($network_admin, $admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_network_detail_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/detail", name="cert_unlp_ngen_network_detail_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @return array
     */
    public function detailNetworkAdminAction(NetworkAdmin $network_admin): array
    {
        return $this->detailEntity($network_admin);
    }

}

Controller/Frontend/Constituency/NetworkEntityFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of NetworkEntityFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Constituency;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkEntity;
use CertUnlp\NgenBundle\Form\Constituency\NetworkEntityType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NetworkEntityFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_network_network_entity_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): array
    {
        return $this->homeEntity($request, $elastica_finder_network_entity);
    }

    /**
     * @Route("search/autocomplete", name="cert_unlp_ngen_network_entity_search_autocomplete")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return JsonResponse
     */
    public function searchAutocompleteNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): JsonResponse
    {
        return $this->searchAutocompleteEntity($request, $elastica_finder_network_entity);

    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/home.html.twig")
     * @Route("search", name="cert_unlp_ngen_network_entity_search")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return array
     */
    public function searchNetworkEntityAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): array
    {
        return $this->searchEntity($request, $elastica_finder_network_entity);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_network_entity_new")
     * @param NetworkEntityType $entity_type
     * @return array
     */
    public function newNetworkEntityAction(NetworkEntityType $entity_type): array
    {
        return $this->newEntity($entity_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_network_entity_edit_id",requirements={"id"="\d+"})
     * @Route("{slug}/edit", name="cert_unlp_ngen_network_entity_edit_slug")
     * @param NetworkEntity $network_entity
     * @param NetworkEntityType $entity_type
     * @return array
     */
    public function editNetworkEntityAction(NetworkEntity $network_entity, NetworkEntityType $entity_type): array
    {
        return $this->editEntity($network_entity, $entity_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_network_entity_detail_id",requirements={"id"="\d+"})
     * @Route("{slug}/detail", name="cert_unlp_ngen_network_entity_detail_slug")
     * @param NetworkEntity $network_entity
     * @return array
     */
    public function detailNetworkEntityAction(NetworkEntity $network_entity): array
    {
        return $this->detailEntity($network_entity);
    }

}

Controller/Frontend/DashboardController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Controller\Frontend;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class DashboardController extends AbstractController
{
    /**
     * @var string
     */
    private $grafana_internal_url;
    /**
     * @var string
     */
    private $grafana_external_url;

    /**
     * DashboardController constructor.
     * @param string $grafana_internal_url
     * @param string $grafana_external_url
     */
    public function __construct(string $grafana_internal_url, string $grafana_external_url)
    {
        $this->grafana_internal_url = $grafana_internal_url;
        $this->grafana_external_url = $grafana_external_url;
    }

    /**
     * @Template("CertUnlpNgenBundle:Dashboard:frontend.html.twig")
     * @Route("/internal",name="cert_unlp_ngen_dashboard_internal")
     * @param Request $request
     * @return array
     */
    public function homeAction(Request $request): array
    {
        return array("dashboard" => $this->getGrafanaInternalUrl());
    }

    /**
     * @return string
     */
    public function getGrafanaInternalUrl(): string
    {
        return $this->grafana_internal_url;
    }

    /**
     * @Template("CertUnlpNgenBundle:Dashboard:frontend.html.twig")
     * @Route("/external",name="cert_unlp_ngen_dashboard_external")
     * @param Request $request
     * @return array
     */
    public function externalAction(Request $request): array
    {
        return array("dashboard" => $this->getGrafanaExternalUrl());
    }

    /**
     * @return string
     */
    public function getGrafanaExternalUrl(): string
    {
        return $this->grafana_external_url;
    }

}

Controller/Frontend/Incident/IncidentDecisionFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */


namespace CertUnlp\NgenBundle\Controller\Frontend\Incident;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Incident\IncidentDecision;
use CertUnlp\NgenBundle\Form\Incident\IncidentDecisionType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class IncidentDecisionFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_incident_decision_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_decision
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_decision): array
    {
        return $this->homeEntity($request, $elastica_finder_decision);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/home.html.twig")
     * @Route("search", name="cert_unlp_ngen_incident_decision_search")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_decision
     * @return array
     */
    public function searchIncidentDecisionAction(Request $request, PaginatedFinderInterface $elastica_finder_decision): array
    {
        return $this->searchEntity($request, $elastica_finder_decision);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/incidentDecisionForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_incident_decision_new")
     * @param IncidentDecisionType $type
     * @return array
     */
    public function newIncidentDecisionAction(IncidentDecisionType $type): array
    {
        return $this->newEntity($type);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/incidentDecisionForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_incident_decision_edit",requirements={"id"="\d+"})
     * @param IncidentDecision $incident_decision
     * @param IncidentDecisionType $type
     * @return array
     */
    public function editIncidentDecisionAction(IncidentDecision $incident_decision, IncidentDecisionType $type): array
    {
        return $this->editEntity($incident_decision, $type);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/incidentDecisionDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_incident_decision_detail",requirements={"id"="\d+"})
     * @param IncidentDecision $incident_decision
     * @return array
     */
    public function detailIncidentDecisionAction(IncidentDecision $incident_decision): array
    {
        return $this->detailEntity($incident_decision);
    }

}

Controller/Frontend/Incident/IncidentDetectedFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 * 
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 * 
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of IncidentStateFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Incident;

use CertUnlp\NgenBundle\Entity\Incident\IncidentDetected;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IncidentDetectedFrontendController extends AbstractController
{
    /**
     * @var string
     */
    private $evidence_path;

    public function __construct(string $evidence_path)
    {
        $this->evidence_path = $evidence_path;
    }

    /**
     * @Route("{id}/evidence_detected", name="cert_unlp_ngen_incident_frontend_evidence_incident_detected_id", requirements={"id"="\d+"})
     * @Route("{slug}/evidence_detected", name="cert_unlp_ngen_incident_detected_frontend_evidence_incident_detected_slug")
     * @param IncidentDetected $detection
     * @return Response
     */
    public function evidenceIncidentDetectedAction(IncidentDetected $detection): Response
    {
        $evidence_file = $this->getEvidencePath() . '/' . $detection->getEvidenceFilePath();
        if (file_exists($evidence_file)) {
            $response = new Response(file_get_contents($evidence_file));
            $response->headers->set('Content-Type', 'application/zip');
            $response->headers->set('Content-Disposition', 'attachment;filename="' . $evidence_file . '"');
            $response->headers->set('Content-length', filesize($evidence_file));
        } else {
            throw $this->createNotFoundException();
        }

        return $response;
    }

    /**
     * @return string
     */
    public function getEvidencePath(): string
    {
        return $this->evidence_path;
    }
}

Resources/views/Incident/Frontend/comments/comment.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% set view = view|default('tree') %}
{% set depth = depth|default(0) %}

{% include '@CertUnlpNgen/Incident/Frontend/comments/comment_content.html.twig' %}

Resources/views/Incident/Frontend/comments/comment_content.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% block fos_comment_comment %}
<div id="fos_comment_{{ comment.id }}" class="fos_comment_comment_show fos_comment_comment_depth_{{ depth }}" {% if parent is defined and parent is not null %}data-parent="{{ parent.id }}"{% endif %}>

    <div class="fos_comment_comment_metas">
        {% block fos_comment_comment_metas %}
            {% block fos_comment_comment_metas_authorline %}
                {% trans from 'FOSCommentBundle' %}fos_comment_comment_show_by{% endtrans %}
                <span class="fos_comment_comment_authorname">
                    {% if comment is fos_comment_in_state(constant('FOS\\CommentBundle\\Model\\CommentInterface::STATE_DELETED')) %}
                {% trans from 'FOSCommentBundle' %}fos_comment_comment_deleted{% endtrans %}
                    {% else %}
                        {{ comment.authorName }}
                    {% endif %}
                </span> - {{ comment.createdAt|date }}
            {% endblock fos_comment_comment_metas_authorline %}

            {% block fos_comment_comment_metas_edit %}
                {% if fos_comment_can_edit_comment(comment) %}
                <button data-container="#fos_comment_comment_body_{{ comment.id }}" data-url="{{ path("fos_comment_edit_thread_comment", {"id": comment.thread.id, "commentId": comment.id}) }}" class="fos_comment_comment_edit_show_form">{% trans from 'FOSCommentBundle' %}fos_comment_comment_edit{% endtrans %}</button>
                {% endif %}
            {% endblock fos_comment_comment_metas_edit %}

            {% block fos_comment_comment_metas_delete %}
                {% if fos_comment_can_delete_comment(comment) %}
                    {% if comment is fos_comment_in_state(constant('FOS\\CommentBundle\\Model\\CommentInterface::STATE_DELETED')) %}
                        {# undelete #}
                        <button data-url="{{ path("fos_comment_remove_thread_comment", {"id": comment.thread.id, "commentId": comment.id, "value": constant('FOS\\CommentBundle\\Model\\CommentInterface::STATE_VISIBLE') }) }}" class="fos_comment_comment_remove">{% trans from 'FOSCommentBundle' %}fos_comment_comment_undelete{% endtrans %}</button>
                    {% else %}
                        {# delete #}
                        <button data-url="{{ path("fos_comment_remove_thread_comment", {"id": comment.thread.id, "commentId": comment.id, "value":  constant('FOS\\CommentBundle\\Model\\CommentInterface::STATE_DELETED')}) }}" class="fos_comment_comment_remove">{% trans from 'FOSCommentBundle' %}fos_comment_comment_delete{% endtrans %}</button>
                    {% endif %}
                {% endif %}
            {% endblock fos_comment_comment_metas_delete %}

            {% block fos_comment_comment_metas_voting %}
                {% if fos_comment_can_vote(comment) %}
                    <div class="fos_comment_comment_voting">
                        <button data-url="{{ path("fos_comment_new_thread_comment_votes", {"id": comment.thread.id, "commentId": comment.id, "value": 1}) }}" class="fos_comment_comment_vote">{% trans from 'FOSCommentBundle' %}fos_comment_comment_show_voteup{% endtrans %}</button>
                        <button data-url="{{ path("fos_comment_new_thread_comment_votes", {"id": comment.thread.id, "commentId": comment.id, "value": -1}) }}" class="fos_comment_comment_vote">{% trans from 'FOSCommentBundle' %}fos_comment_comment_show_votedown{% endtrans %}</button>
                        <div class="fos_comment_comment_score" id="fos_comment_score_{{ comment.id }}">{% include '@CertUnlpNgen/Incident/Frontend/comments/comment_votes.html.twig' with { 'commentScore': comment.score } %}</div>
                    </div>
                {% endif %}
            {% endblock fos_comment_comment_metas_voting %}
        {% endblock fos_comment_comment_metas %}
    </div>

    <div id="fos_comment_comment_body_{{ comment.id }}" class="fos_comment_comment_body">
        {% block fos_comment_comment_body %}
            {% if comment is fos_comment_in_state(constant('FOS\\CommentBundle\\Model\\CommentInterface::STATE_DELETED')) %}
                {% trans from 'FOSCommentBundle' %}fos_comment_comment_deleted{% endtrans %}
            {% else %}
                {% if comment is fos_comment_raw %}
                    {{ comment.rawBody | raw }}
                {% else %}
                    {{ comment.body | nl2br }}
                {% endif %}
            {% endif %}
        {% endblock fos_comment_comment_body %}
    </div>

    {% block fos_comment_comment_children %}
        {% if view is not same as('flat') %}
            {% if fos_comment_can_comment(comment) %}
                <div class="fos_comment_comment_reply">
                    {% block fos_comment_comment_reply %}
                        <button data-url="{{ path('fos_comment_new_thread_comments', {"id": comment.thread.id}) }}" data-name="{{ comment.authorName }}" data-parent-id="{{ comment.id }}" class="fos_comment_comment_reply_show_form">{% trans from 'FOSCommentBundle' %}fos_comment_comment_show_reply{% endtrans %}</button>
                    {% endblock fos_comment_comment_reply %}
                </div>
            {% endif %}

            <div class="fos_comment_comment_replies">

                {% if children is defined %}
                    {% include '@CertUnlpNgen/Incident/Frontend/comments/comments.html.twig' with { "comments": children, "depth": depth + 1, "parent": comment, "view": view } %}
                {% endif %}

            </div>
        {% elseif view is same as('flat') and children is defined %}
            {% include '@CertUnlpNgen/Incident/Frontend/comments/comments.html.twig' with { "comments": children, "depth": depth + 1, "parent": comment, "view": view } %}
        {% endif %}
    {% endblock fos_comment_comment_children %}

</div>
{% endblock fos_comment_comment %}

Resources/views/Incident/Frontend/comments/comment_new_content.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% set first = first|default(false) %}

{% set url_parameters = {'id': id } %}
{% if parent is not null %}
    {% set url_parameters = url_parameters|merge({'parentId': parent.id}) %}
{% endif %}

{% block fos_comment_comment_form_holder %}
    <div class="fos_comment_comment_form_holder">
        {% block fos_comment_form_title %}
            {% if first %}
                <h3>{% trans from 'FOSCommentBundle' %}fos_comment_comment_new_headline_first{% endtrans %}</h3>
            {% elseif parent is not null %}
                <h3>{% trans with {"%name%": parent.authorName } from 'FOSCommentBundle' %}fos_comment_comment_reply_reply_to{% endtrans %}</h3>
            {% else %}
                <h3>{% trans from 'FOSCommentBundle' %}fos_comment_comment_new_headline{% endtrans %}</h3>
            {% endif %}
        {% endblock %}

        {% block fos_comment_comment_new_form %}
            <form class="fos_comment_comment_new_form" action="{{ path('fos_comment_post_thread_comments', url_parameters) }}" data-parent="{{ parent.id|default() }}" method="POST">

                {% block fos_comment_form_fields %}
                    <div class="fos_comment_form_errors">
                    {{ form_errors(form) }}
                    {{ form_errors(form.body) }}
                    </div>
                    {{ form_widget(form.body) }}

                    {{ form_rest(form) }}
                {% endblock %}

                <div class="fos_comment_submit">
                    {% block fos_comment_form_submit %}
                        {% if parent is not null %}
                            <input type="button" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_reply_cancel{% endtrans %}" class="fos_comment_comment_reply_cancel" />
                        {% endif %}
                        <input type="submit" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_new_submit{% endtrans %}" />
                    {% endblock %}
                </div>

            </form>
        {% endblock fos_comment_comment_new_form %}

    </div>
{% endblock fos_comment_comment_form_holder %}

Resources/views/Incident/Frontend/comments/errors.html.twig
<ul>
{% for error in errors %}
    <li>{{ error }}</li>
{% endfor%}
</ul>

Resources/views/Incident/Frontend/comments/thread_xml_feed.rss.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<feed xmlns="http://www.w3.org/2005/Atom">
    <title>{{ thread.id }}</title>
    <id>{{ thread.id }}</id>
    <link href="{{ thread.permalink }}" rel="alternate" />
    <updated>{{ thread.lastCommentAt|date("c") }}</updated>
{% for commentinfo in comments %}
    <entry>
        <title>By {{ commentinfo.comment.authorName }} on {{ commentinfo.comment.createdAt|date }}</title>
        <author>
            <name>{{ commentinfo.comment.authorName }}</name>
        </author>
        <updated>{{ commentinfo.comment.createdAt|date("c") }}</updated>
        <link rel="alternate">{{ thread.permalink }}#{{ commentinfo.comment.id }}</link>
        <summary>{{ commentinfo.comment.body }}</summary>
    </entry>
{% endfor %}
</feed>