Entity/EntityApiFrontend.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Entity;

use CertUnlp\NgenBundle\Model\EntityApiFrontendInterface;
use Closure;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;

/**
 * @JMS\ExclusionPolicy("all")
 * @ORM\MappedSuperclass()
 */
abstract class EntityApiFrontend extends EntityApi implements EntityApiFrontendInterface
{

    /**
     * @return string
     */
    abstract public function getIcon(): string;


    /**
     * @return string
     */
    abstract public function getColor(): string;

    /**
     * @param Collection $collection
     * @param Closure $callback
     * @return array
     */
    public function getRatio(Collection $collection, Closure $callback): array
    {
        $ratio = [];
        foreach ($collection as $colectee) {
            if (isset($ratio[$callback($colectee)])) {
                $ratio[$callback($colectee)]++;
            } else {
                $ratio[$callback($colectee)] = 1;
            }
        }

        $percentages = [];
        foreach ($ratio as $key => $value) {
            $percentages[] = [$key, $value];
        }

        return $percentages;
    }


}

Controller/Frontend/Constituency/NetworkAdminFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 * 
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 * 
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of NetworkAdminFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Constituency;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkAdmin;
use CertUnlp\NgenBundle\Form\Constituency\NetworkAdminType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NetworkAdminFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_network_admin_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->homeEntity($request, $elastica_finder_network_admin);
    }


    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin/Frontend:home.html.twig")
     * @Route("search", name="cert_unlp_ngen_network_search_network_admin")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function searchNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->searchEntity($request, $elastica_finder_network_admin);
    }

    /**
     * @Route("search/autocomplete", name="cert_unlp_ngen_network_admin_search_autocomplete")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return JsonResponse
     */
    public function searchAutocompleteNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): JsonResponse
    {
        return $this->searchAutocompleteEntity($request, $elastica_finder_network_admin);

    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_network_new_network_admin")
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function newNetworkAdminAction(NetworkAdminType $admin_type): array
    {
        return $this->newEntity($admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_network_edit_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/edit", name="cert_unlp_ngen_network_edit_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function editNetworkAdminAction(NetworkAdmin $network_admin, NetworkAdminType $admin_type): array
    {
        return $this->editEntity($network_admin, $admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_network_detail_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/detail", name="cert_unlp_ngen_network_detail_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @return array
     */
    public function detailNetworkAdminAction(NetworkAdmin $network_admin): array
    {
        return $this->detailEntity($network_admin);
    }

}

Controller/Frontend/Constituency/NetworkEntityFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of NetworkEntityFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Constituency;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkEntity;
use CertUnlp\NgenBundle\Form\Constituency\NetworkEntityType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NetworkEntityFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_network_network_entity_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): array
    {
        return $this->homeEntity($request, $elastica_finder_network_entity);
    }

    /**
     * @Route("search/autocomplete", name="cert_unlp_ngen_network_entity_search_autocomplete")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return JsonResponse
     */
    public function searchAutocompleteNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): JsonResponse
    {
        return $this->searchAutocompleteEntity($request, $elastica_finder_network_entity);

    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/home.html.twig")
     * @Route("search", name="cert_unlp_ngen_network_entity_search")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_entity
     * @return array
     */
    public function searchNetworkEntityAction(Request $request, PaginatedFinderInterface $elastica_finder_network_entity): array
    {
        return $this->searchEntity($request, $elastica_finder_network_entity);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_network_entity_new")
     * @param NetworkEntityType $entity_type
     * @return array
     */
    public function newNetworkEntityAction(NetworkEntityType $entity_type): array
    {
        return $this->newEntity($entity_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_network_entity_edit_id",requirements={"id"="\d+"})
     * @Route("{slug}/edit", name="cert_unlp_ngen_network_entity_edit_slug")
     * @param NetworkEntity $network_entity
     * @param NetworkEntityType $entity_type
     * @return array
     */
    public function editNetworkEntityAction(NetworkEntity $network_entity, NetworkEntityType $entity_type): array
    {
        return $this->editEntity($network_entity, $entity_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkEntity:Frontend/networkEntityDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_network_entity_detail_id",requirements={"id"="\d+"})
     * @Route("{slug}/detail", name="cert_unlp_ngen_network_entity_detail_slug")
     * @param NetworkEntity $network_entity
     * @return array
     */
    public function detailNetworkEntityAction(NetworkEntity $network_entity): array
    {
        return $this->detailEntity($network_entity);
    }

}

Controller/Frontend/DashboardController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Controller\Frontend;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class DashboardController extends AbstractController
{
    /**
     * @var string
     */
    private $grafana_internal_url;
    /**
     * @var string
     */
    private $grafana_external_url;

    /**
     * DashboardController constructor.
     * @param string $grafana_internal_url
     * @param string $grafana_external_url
     */
    public function __construct(string $grafana_internal_url, string $grafana_external_url)
    {
        $this->grafana_internal_url = $grafana_internal_url;
        $this->grafana_external_url = $grafana_external_url;
    }

    /**
     * @Template("CertUnlpNgenBundle:Dashboard:frontend.html.twig")
     * @Route("/internal",name="cert_unlp_ngen_dashboard_internal")
     * @param Request $request
     * @return array
     */
    public function homeAction(Request $request): array
    {
        return array("dashboard" => $this->getGrafanaInternalUrl());
    }

    /**
     * @return string
     */
    public function getGrafanaInternalUrl(): string
    {
        return $this->grafana_internal_url;
    }

    /**
     * @Template("CertUnlpNgenBundle:Dashboard:frontend.html.twig")
     * @Route("/external",name="cert_unlp_ngen_dashboard_external")
     * @param Request $request
     * @return array
     */
    public function externalAction(Request $request): array
    {
        return array("dashboard" => $this->getGrafanaExternalUrl());
    }

    /**
     * @return string
     */
    public function getGrafanaExternalUrl(): string
    {
        return $this->grafana_external_url;
    }

}

Controller/Frontend/Incident/IncidentDecisionFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */


namespace CertUnlp\NgenBundle\Controller\Frontend\Incident;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Incident\IncidentDecision;
use CertUnlp\NgenBundle\Form\Incident\IncidentDecisionType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class IncidentDecisionFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_incident_decision_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_decision
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_decision): array
    {
        return $this->homeEntity($request, $elastica_finder_decision);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/home.html.twig")
     * @Route("search", name="cert_unlp_ngen_incident_decision_search")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_decision
     * @return array
     */
    public function searchIncidentDecisionAction(Request $request, PaginatedFinderInterface $elastica_finder_decision): array
    {
        return $this->searchEntity($request, $elastica_finder_decision);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/incidentDecisionForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_incident_decision_new")
     * @param IncidentDecisionType $type
     * @return array
     */
    public function newIncidentDecisionAction(IncidentDecisionType $type): array
    {
        return $this->newEntity($type);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/incidentDecisionForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_incident_decision_edit",requirements={"id"="\d+"})
     * @param IncidentDecision $incident_decision
     * @param IncidentDecisionType $type
     * @return array
     */
    public function editIncidentDecisionAction(IncidentDecision $incident_decision, IncidentDecisionType $type): array
    {
        return $this->editEntity($incident_decision, $type);
    }

    /**
     * @Template("CertUnlpNgenBundle:IncidentDecision:Frontend/incidentDecisionDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_incident_decision_detail",requirements={"id"="\d+"})
     * @param IncidentDecision $incident_decision
     * @return array
     */
    public function detailIncidentDecisionAction(IncidentDecision $incident_decision): array
    {
        return $this->detailEntity($incident_decision);
    }

}

Controller/Frontend/Incident/IncidentDetectedFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 * 
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 * 
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of IncidentStateFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Incident;

use CertUnlp\NgenBundle\Entity\Incident\IncidentDetected;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IncidentDetectedFrontendController extends AbstractController
{
    /**
     * @var string
     */
    private $evidence_path;

    public function __construct(string $evidence_path)
    {
        $this->evidence_path = $evidence_path;
    }

    /**
     * @Route("{id}/evidence_detected", name="cert_unlp_ngen_incident_frontend_evidence_incident_detected_id", requirements={"id"="\d+"})
     * @Route("{slug}/evidence_detected", name="cert_unlp_ngen_incident_detected_frontend_evidence_incident_detected_slug")
     * @param IncidentDetected $detection
     * @return Response
     */
    public function evidenceIncidentDetectedAction(IncidentDetected $detection): Response
    {
        $evidence_file = $this->getEvidencePath() . '/' . $detection->getEvidenceFilePath();
        if (file_exists($evidence_file)) {
            $response = new Response(file_get_contents($evidence_file));
            $response->headers->set('Content-Type', 'application/zip');
            $response->headers->set('Content-Disposition', 'attachment;filename="' . $evidence_file . '"');
            $response->headers->set('Content-length', filesize($evidence_file));
        } else {
            throw $this->createNotFoundException();
        }

        return $response;
    }

    /**
     * @return string
     */
    public function getEvidencePath(): string
    {
        return $this->evidence_path;
    }
}

Resources/views/IncidentTaxonomyValue/Frontend/list/incidentTaxonomyValueList.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            <strong>{{ 'Showing'|trans }}</strong>
            <strong>({{ objects.getPaginationData.lastItemNumber~"/"~objects.getTotalItemCount }})</strong>
        </h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="tabla_hosts" class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr role="row">
                    <th>{{ 'Action'| trans }}</th>
                    <th>{{ knp_pagination_sortable(objects, 'Active'|trans, 'active') }}</th>
                    <th>{{ knp_pagination_sortable(objects, 'Name'|trans, 'name') }}</th>
{#                    <th>{{ knp_pagination_sortable(objects, 'Description'|trans, 'description') }}</th>#}
                    <th>{{ knp_pagination_sortable(objects, 'Predicate'|trans, 'predicate') }}</th>
                    <th>{{ knp_pagination_sortable(objects, 'Version'|trans, 'version') }}</th>
                    <th>{{ knp_pagination_sortable(objects, 'Created'|trans, 'created') }}</th>
                    <th>{{ knp_pagination_sortable(objects, 'Updated'|trans, 'updated') }}</th>
                </tr>
                </thead>
                <tbody>
                {% for incidentTaxonomyValue in incidentTaxonomyValues %}
                    {% include 'CertUnlpNgenBundle:IncidentTaxonomyValue:Frontend/list/incidentTaxonomyValueListRow.html.twig' with {'incidentTaxonomyValue': incidentTaxonomyValue} %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="pagination justify-content-center">
    {{ knp_pagination_render(incidentTaxonomyValues, null, {}, { "prev_label": "Previous"|trans, "next_label": "Next"|trans, "first_label": "First"|trans, "last_label": "Last"|trans}) }}
</div>

Resources/views/IncidentTaxonomyValue/Frontend/list/incidentTaxonomyValueListRow.html.twig
{#
This file is part of the Ngen - CSIRT Incident Report System.

(c) CERT UNLP <support@cert.unlp.edu.ar>

This source file is subject to the GPL v3.0 license that is bundled
with this source code in the file LICENSE.
#}
{% import '@CertUnlpNgen/Frontend/detailMacros.html.twig' as print %}

<tr data-id="{{ incidentTaxonomyValue.slug }}">
    <td class="text-center">
        {% include '@CertUnlpNgen/Frontend/list/listDropdown.html.twig' with {'object':incidentTaxonomyValue , 'detail_link': path('cert_unlp_ngen_taxonomy_value_detail',{ 'slug': incidentTaxonomyValue.slug}),'edit_link': path('cert_unlp_ngen_taxonomy_value_edit',{ 'slug': incidentTaxonomyValue.slug})} %}
    </td>
    <td id="state_label_holder" class="text-center">
        {{ print.statusdropbox(incidentTaxonomyValue) }}
    </td>
    <td class="text-center">
        <div class="float-left">
            {{ print.colordropbox(incidentTaxonomyValue.color,incidentTaxonomyValue.icon,incidentTaxonomyValue.name,'#',incidentTaxonomyValue.name) }}
        </div>
    </td>
    <td class="text-center">
        {% if incidentTaxonomyValue.predicate %}
            <div class="float-left">
                {{ print.colordropbox(incidentTaxonomyValue.predicate.color,incidentTaxonomyValue.predicate.icon,incidentTaxonomyValue.predicate| trans,path('cert_unlp_ngen_taxonomy_predicate_detail',{'slug': incidentTaxonomyValue.predicate.slug}),incidentTaxonomyValue.predicate) }}
            </div>
        {% endif %}
    </td>
    <td class="text-center">
        {{ print.colordropbox('primary','code-branch',incidentTaxonomyValue.version,'#',incidentTaxonomyValue.version) }}
    </td>
    <td class="text-center">
        <small>
            {{ print.colordropbox('primary','calendar-alt',incidentTaxonomyValue.createdAt|date('Y-m-d'),'#',incidentTaxonomyValue.createdAt|date('Y-m-d')) }}
        </small>
    </td>
    <td class="text-center">
        <small>
            {{ print.colordropbox('primary','calendar-alt',incidentTaxonomyValue.updatedAt|date('Y-m-d'),'#',incidentTaxonomyValue.updatedAt|date('Y-m-d')) }}
        </small>
    </td>
</tr>

Resources/views/IncidentTaxonomyValue/Frontend/list/stateLabel.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}

{% if incidentTaxonomyValue.isActive %}
    {{ label_success("active"|trans) }}
{% else %}
    {{ label_danger("innactive"|trans) }}
{% endif %}