Entity/EntityApiFrontend.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Entity;

use CertUnlp\NgenBundle\Model\EntityApiFrontendInterface;
use Closure;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;

/**
 * @JMS\ExclusionPolicy("all")
 * @ORM\MappedSuperclass()
 */
abstract class EntityApiFrontend extends EntityApi implements EntityApiFrontendInterface
{

    /**
     * @return string
     */
    abstract public function getIcon(): string;


    /**
     * @return string
     */
    abstract public function getColor(): string;

    /**
     * @param Collection $collection
     * @param Closure $callback
     * @return array
     */
    public function getRatio(Collection $collection, Closure $callback): array
    {
        $ratio = [];
        foreach ($collection as $colectee) {
            if (isset($ratio[$callback($colectee)])) {
                $ratio[$callback($colectee)]++;
            } else {
                $ratio[$callback($colectee)] = 1;
            }
        }

        $percentages = [];
        foreach ($ratio as $key => $value) {
            $percentages[] = [$key, $value];
        }

        return $percentages;
    }


}

Entity/Incident/Incident.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Entity\Incident;

use CertUnlp\NgenBundle\Entity\Communication\Contact\Contact;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkAdmin;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkElement\Host;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkElement\Network;
use CertUnlp\NgenBundle\Entity\Entity;
use CertUnlp\NgenBundle\Entity\EntityApiFrontend;
use CertUnlp\NgenBundle\Entity\Incident\State\Behavior\StateBehavior;
use CertUnlp\NgenBundle\Entity\Incident\State\Edge\StateEdge;
use CertUnlp\NgenBundle\Entity\Incident\State\IncidentState;
use CertUnlp\NgenBundle\Entity\User\User;
use CertUnlp\NgenBundle\Validator\Constraints as CustomAssert;
use DateInterval;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use FOS\CommentBundle\Model\Thread;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as JMS;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="CertUnlp\NgenBundle\Repository\Incident\IncidentRepository")
 * @ORM\EntityListeners({"CertUnlp\NgenBundle\Service\Listener\Entity\IncidentListener"})
 * @ORM\HasLifecycleCallbacks
 * @JMS\ExclusionPolicy("all")
 * @CustomAssert\HasReport()
 */
class Incident extends EntityApiFrontend
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @JMS\Expose
     * @JMS\Groups({"read"})
     */
    protected $id;
    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"id"},separator="_")
     * @ORM\Column(name="slug", type="string", length=100,nullable=true)
     * @JMS\Expose
     * @JMS\Groups({"read"})
     * */
    protected $slug;
    /**
     * @var string
     * @ORM\Column(type="text",nullable=true)
     */
    protected $raw = null;
    /**
     * @var DateTime
     *
     * @ORM\Column(name="response_dead_line", type="datetime",nullable=true))
     * @JMS\Type("DateTime<'Y-m-d h:m:s'>")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     */
    private $responseDeadLine;
    /**
     * @var DateTime
     *
     * @ORM\Column(name="solve_dead_line", type="datetime",nullable=true))
     * @JMS\Expose
     * @JMS\Type("DateTime<'Y-m-d h:m:s'>")
     * @JMS\Groups({"read","write"})
     */
    private $solveDeadLine;
    /**
     * @var User
     * @CustomAssert\EntityNotActive()
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\User\User", inversedBy="incidents")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     */
    private $reporter;
    /**
     * @var User
     * @CustomAssert\EntityNotActive()
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\User\User", inversedBy="assignedIncidents")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     */
    private $assigned;
    /**
     * @var IncidentType
     * @CustomAssert\EntityNotActive()
     * @JMS\Expose
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentType",inversedBy="incidents")
     * @ORM\JoinColumn(name="type", referencedColumnName="slug")
     * @JMS\Groups({"read","write","fundamental"})
     * @JMS\MaxDepth(depth=1)
     */
    private $type;
    /**
     * @var IncidentFeed
     * @CustomAssert\EntityNotActive()
     * @Assert\NotNull
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentFeed", inversedBy="incidents")
     * @ORM\JoinColumn(name="feed", referencedColumnName="slug")
     * @JMS\Expose
     * @JMS\Groups({"read","write","fundamental"})
     */
    private $feed;
    /**
     * @var IncidentState
     * @CustomAssert\EntityNotActive()
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\State\IncidentState", inversedBy="incidents")
     * @ORM\JoinColumn(name="state", referencedColumnName="slug")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     * @JMS\MaxDepth(depth=1)
     */
    private $state;
    /**
     * @var IncidentState
     * @CustomAssert\EntityNotActive()
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\State\IncidentState")
     * @ORM\JoinColumn(name="unresponded_state", referencedColumnName="slug")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     * @JMS\MaxDepth(depth=1)
     */
    private $unrespondedState;
    /**
     * @var IncidentState
     * @CustomAssert\EntityNotActive()
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\State\IncidentState")
     * @ORM\JoinColumn(name="unsolved_state", referencedColumnName="slug")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     * @JMS\MaxDepth(depth=1)
     */
    private $unsolvedState;
    /**
     * @var IncidentTlp
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentTlp", inversedBy="incidents")
     * @ORM\JoinColumn(name="tlp_state", referencedColumnName="slug")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     */
    private $tlp;
    /**
     * @var IncidentPriority
     * @CustomAssert\EntityNotActive()
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentPriority", inversedBy="incidents")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     * @JMS\MaxDepth(depth=1)
     */
    private $priority;
    /**
     * @var IncidentImpact
     * @CustomAssert\EntityNotActive()
     */
    private $impact = null;
    /**
     * @var IncidentUrgency
     * @CustomAssert\EntityNotActive()
     */
    private $urgency = null;
    /**
     * @var IncidentCommentThread
     * @ORM\OneToOne(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentCommentThread",mappedBy="incident",fetch="EXTRA_LAZY"))
     */
    private $comment_thread;
    /**
     * @var DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     * @JMS\Expose
     * @JMS\Type("DateTime<'Y-m-d h:m:s'>")
     * @JMS\Groups({"read","write"})
     */
    private $date;
    /**
     * @var Collection
     * @JMS\Expose
     * @ORM\OneToMany(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentDetected",mappedBy="incident",cascade={"persist"},orphanRemoval=true)
     * @JMS\Groups({"read","write"})
     * @JMS\MaxDepth(depth=2)
     */
    private $incidentsDetected;
    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="CertUnlp\NgenBundle\Entity\Incident\IncidentStateChange",mappedBy="incident",cascade={"persist"},orphanRemoval=true)
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     * @JMS\MaxDepth(depth=2)
     */
    private $state_changes;
    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="CertUnlp\NgenBundle\Entity\Communication\Message\Message",mappedBy="incident")
     * @JMS\Expose
     * @JMS\Groups({"read"})
     */
    private $messages;
    /**
     * @var DateTime
     *
     * @ORM\Column(name="renotification_date", type="datetime",nullable=true)
     * @JMS\Type("DateTime<'Y-m-d h:m:s'>")
     */
    private $renotificationDate;
    /**
     * @var Host|null
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Constituency\NetworkElement\Host", inversedBy="incidents")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     */
    private $origin;
    /**
     * @var Network|null
     * @ORM\ManyToOne(targetEntity="CertUnlp\NgenBundle\Entity\Constituency\NetworkElement\Network", inversedBy="incidents")
     * @JMS\Expose
     * @JMS\Groups({"read","write"})
     */
    private $network;
    /**
     * @var boolean
     */
    private $needToCommunicate = false;
    /**
     * @Assert\File(maxSize = "5M")
     */
    private $evidence_file;
    /**
     * @ORM\Column(name="evidence_file_path", type="string",nullable=true)
     */
    private $evidence_file_path;
    /**
     * @var string
     * @ORM\Column(name="report_message_id", type="string",nullable=true)
     */
    private $report_message_id;
    /**
     * @var bool
     */
    private $notSendReport = false;
    /**
     * @var string
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes;
    /**
     * @ORM\Column(name="ltd_count", type="integer")
     */
    private $ltdCount = 0;
    /**
     * @CustomAssert\ValidAddress()
     * @JMS\Expose
     * @JMS\Groups({"read","write","fundamental"})
     */
    private $address;
    /**
     * @var User
     * @CustomAssert\EntityNotActive()
     */
    private $responsable;

    /**
     * Incident constructor.
     * @param string|null $term
     */
    public function __construct(string $term = null)
    {
        if ($term) {
            $this->setAddress($term);
        }
        $this->incidentsDetected = new ArrayCollection();
        $this->state_changes = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getRaw(): ?string
    {
        return $this->raw;
    }

    /**
     * @param string $raw
     * @return Incident
     */
    public function setRaw(string $raw): Incident
    {
        $this->setter($this->raw, $raw);
        return $this;
    }

    /**
     * @param mixed $property
     * @param mixed $value
     * @param bool $fundamental
     * @return bool
     */
    public function setter(&$property, $value, bool $fundamental = false): bool
    {
        if ($this->getBehavior()) {
            return $this->getBehavior()->setter($property, $value, $fundamental);
        }
        $property = $value;
        return true;
    }

    /**
     * @return StateBehavior
     */
    public function getBehavior(): ?StateBehavior
    {

Controller/Frontend/Constituency/NetworkAdminFrontendController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 * 
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 * 
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Description of NetworkAdminFrontendController
 *
 * @author dam
 */

namespace CertUnlp\NgenBundle\Controller\Frontend\Constituency;

use CertUnlp\NgenBundle\Controller\Frontend\FrontendController;
use CertUnlp\NgenBundle\Entity\Constituency\NetworkAdmin;
use CertUnlp\NgenBundle\Form\Constituency\NetworkAdminType;
use FOS\ElasticaBundle\Finder\PaginatedFinderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NetworkAdminFrontendController extends FrontendController
{

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/home.html.twig")
     * @Route("/", name="cert_unlp_ngen_network_admin_frontend_home")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function homeAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->homeEntity($request, $elastica_finder_network_admin);
    }


    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin/Frontend:home.html.twig")
     * @Route("search", name="cert_unlp_ngen_network_search_network_admin")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return array
     */
    public function searchNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): array
    {
        return $this->searchEntity($request, $elastica_finder_network_admin);
    }

    /**
     * @Route("search/autocomplete", name="cert_unlp_ngen_network_admin_search_autocomplete")
     * @param Request $request
     * @param PaginatedFinderInterface $elastica_finder_network_admin
     * @return JsonResponse
     */
    public function searchAutocompleteNetworkAdminAction(Request $request, PaginatedFinderInterface $elastica_finder_network_admin): JsonResponse
    {
        return $this->searchAutocompleteEntity($request, $elastica_finder_network_admin);

    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("/new", name="cert_unlp_ngen_network_new_network_admin")
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function newNetworkAdminAction(NetworkAdminType $admin_type): array
    {
        return $this->newEntity($admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminForm.html.twig")
     * @Route("{id}/edit", name="cert_unlp_ngen_network_edit_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/edit", name="cert_unlp_ngen_network_edit_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @param NetworkAdminType $admin_type
     * @return array
     */
    public function editNetworkAdminAction(NetworkAdmin $network_admin, NetworkAdminType $admin_type): array
    {
        return $this->editEntity($network_admin, $admin_type);
    }

    /**
     * @Template("CertUnlpNgenBundle:NetworkAdmin:Frontend/networkAdminDetail.html.twig")
     * @Route("{id}/detail", name="cert_unlp_ngen_network_detail_network_admin_id",requirements={"id"="\d+"})
     * @Route("{slug}/detail", name="cert_unlp_ngen_network_detail_network_admin_slug")
     * @param NetworkAdmin $network_admin
     * @return array
     */
    public function detailNetworkAdminAction(NetworkAdmin $network_admin): array
    {
        return $this->detailEntity($network_admin);
    }

}

Controller/Frontend/DashboardController.php
<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Controller\Frontend;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class DashboardController extends AbstractController
{
    /**
     * @var string
     */
    private $grafana_internal_url;
    /**
     * @var string
     */
    private $grafana_external_url;

    /**
     * DashboardController constructor.
     * @param string $grafana_internal_url
     * @param string $grafana_external_url
     */
    public function __construct(string $grafana_internal_url, string $grafana_external_url)
    {
        $this->grafana_internal_url = $grafana_internal_url;
        $this->grafana_external_url = $grafana_external_url;
    }

    /**
     * @Template("CertUnlpNgenBundle:Dashboard:frontend.html.twig")
     * @Route("/internal",name="cert_unlp_ngen_dashboard_internal")
     * @param Request $request
     * @return array
     */
    public function homeAction(Request $request): array
    {
        return array("dashboard" => $this->getGrafanaInternalUrl());
    }

    /**
     * @return string
     */
    public function getGrafanaInternalUrl(): string
    {
        return $this->grafana_internal_url;
    }

    /**
     * @Template("CertUnlpNgenBundle:Dashboard:frontend.html.twig")
     * @Route("/external",name="cert_unlp_ngen_dashboard_external")
     * @param Request $request
     * @return array
     */
    public function externalAction(Request $request): array
    {
        return array("dashboard" => $this->getGrafanaExternalUrl());
    }

    /**
     * @return string
     */
    public function getGrafanaExternalUrl(): string
    {
        return $this->grafana_external_url;
    }

}

Resources/views/Incident/Frontend/list/actionsLabel.html.twig
{#
This file is part of the Ngen - CSIRT Incident Report System.

(c) CERT UNLP <support@cert.unlp.edu.ar>

This source file is subject to the GPL v3.0 license that is bundled
with this source code in the file LICENSE.
#}
<div class="btn-group inline pull-left dropdown action-dropdown">
    <a class="btn btn-sm btn-primary"
       href="{{ path('cert_unlp_ngen_internal_incident_frontend_detail_incident',{'slug':incident.id}) }}"
       title="{{ 'Details'|trans }}">
        {{ icon('eye') }}
    </a>
    <a class="btn btn-sm btn-primary" role="button"
       href="{{ path('cert_unlp_ngen_internal_incident_frontend_edit_incident_id',{'id': incident.id}) }}"
       title=" {{ 'Edit'|trans }}">
        {{ icon('edit') }}
    </a>

    <button class="btn btn-sm btn-primary ladda-button dropdown-toggle" data-style="slide-down" type="button"
            id="dropdownMenu1" data-toggle="dropdown" aria-expanded="false">
        {{ icon('menu') }}
        <span class="caret"></span>
    </button>

    <div class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        {% for state in incident.state.newStates %}
            {% if state.slug != incident.state.slug %}
                <a class="state-label dropdown-item" data-state-slug="{{ state.slug }}"
                   data-state-name="{{ state.name }}" tabindex="-1"
                   href="#">
                    {{ icon('fas fa-'~state.behavior.icon~' text-'~state.behavior.color) }}
                    <span class="action-text">{{ state.name |trans }}</span>
                </a>
            {% endif %}
        {% endfor %}
    </div>

</div>

Resources/views/Incident/Frontend/list/comments.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<div id="fos_comment_thread"></div>

<script>
    // thread id12312321
    var fos_comment_thread_id = '{{ id }}';
    var fos_comment_thread_view = '{{ view|default('tree') }}';

    // api base url to use for initial requests
    fos_comment_thread_api_base_url = '{{ path('fos_comment_get_threads') }}';

    // Snippet for asynchronously loading the comments
    (function () {
        var fos_comment_script = document.createElement('script');
        fos_comment_script.async = true;
        fos_comment_script.src = '{{ asset('bundles/foscomment/js/comments.js') }}';

        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(fos_comment_script);
    })();
</script>

Resources/views/Incident/Frontend/list/filterHeadersPaginator.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}
    <th class="text-center header">{{ 'Actions'|trans }}</th>
    <th class="text-center header">Time</th>
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'Date'| trans, 'date') }}</th>
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'Address'| trans , 'address') }}</th>
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'Type'| trans, 'type') }}</th>
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'State'| trans, 'state') }}</th>
{#    <th class="text-center header">{{ knp_pagination_sortable(objects, 'TLP'| trans, 'tlp') }}</th>#}
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'Priority'| trans, 'priority') }}</th>
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'Feed'| trans, 'feed') }}</th>
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'Updated'| trans, 'updated') }}</th>
{#    <th class="text-center header">{{ knp_pagination_sortable(objects, 'Reports'| trans, 'ltdCount') }}</th>#}
    <th class="text-center header sortable">{{ knp_pagination_sortable(objects, 'Reporter'| trans , 'reporter') }}</th>

Resources/views/Incident/Frontend/list/filterList.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}
{% for incident in objects %}
    {% block list_body %}
        {% include 'CertUnlpNgenBundle:Incident:Frontend/list/incidentListRow.html.twig' with {'incident': incident} %}
    {% endblock %}
{% endfor %}

Resources/views/Incident/Frontend/list/filterListPaginator.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}

{{ knp_pagination_render(objects, null, {}, { "prev_label": "Previous" | trans , "next_label": "Next"| trans, "first_label": "First"| trans, "last_label": "Last"| trans}) }}

Resources/views/Incident/Frontend/list/incidentListRow.html.twig
{#
This file is part of the Ngen - CSIRT Incident Report System.

(c) CERT UNLP <support@cert.unlp.edu.ar>

This source file is subject to the GPL v3.0 license that is bundled
with this source code in the file LICENSE.
#}
{% import '@CertUnlpNgen/Frontend/detailMacros.html.twig' as print %}

<tr data-id="{{ incident.id }}" role="row">

    <td class="text-center">
        {% include "CertUnlpNgenBundle:Incident:Frontend/list/actionsLabel.html.twig" with {'incident': incident,'incidentsDetected':incident.incidentsDetected} %}
    </td>
    <td id="state_label_holder" class="text-center">
        {% include "CertUnlpNgenBundle:Incident/Frontend:incidentTimeMacro.html.twig" with {'incident': incident,'type':'label_list', 'response': true} %}
        {% if incident.respondedDate %}
            {% include "CertUnlpNgenBundle:Incident/Frontend:incidentTimeMacro.html.twig" with {'incident': incident,'type':'label_list', 'response': false} %}
        {% endif %}
    </td>
    <td class="text-center">
        <small>
            {{ print.colordropbox('primary','calendar-alt',incident.date|date('Y-m-d'),'#',incident.date|date('Y-m-d')) }}
        </small>
    </td>
    <td class="text-center">
        {% if incident.origin %}
            <div class="float-left">
                {{ print.colordropbox(incident.origin.color,incident.origin.icon,incident.address,path('cert_unlp_ngen_host_detail_host_id',{'id': incident.origin.id}),incident.origin.address) }}
            </div>
        {% endif %}
    </td>
    <td class="text-center">
        <div class="float-left">
            {{ print.colordropbox(incident.type.color(lang),incident.type.icon,incident.type,path('cert_unlp_ngen_incident_type_detail',{'slug': incident.type.slug}),incident.type) }}
        </div>
    </td>
    <td id="state_label_holder" class="text-center">
        <small>
            {{ print.colordropbox(incident.state.color,incident.state.icon,incident.state,path('cert_unlp_ngen_incident_state_detail',{'slug': incident.state.slug}),incident.state) }}
        </small>
    </td>

    {# <td id="tlp_label_holder" class="text-center"> #}
    {# {{ print.colordropbox(incident.tlp.color,incident.tlp.icon,incident.tlp.name,'#',incident.tlp) }} #}
    {# </td> #}
    <td class="text-center">
        {{ print.colordropbox(incident.priority.color,incident.priority.icon,incident.priority,path('cert_unlp_ngen_incident_priority_detail',{'id': incident.priority.id}),incident.priority) }}
    </td>

    <td class="text-center">
        <div class="float-left">
            {{ print.colordropbox(incident.feed.color,incident.feed.icon,incident.feed,path('cert_unlp_ngen_incident_feed_detail',{'slug': incident.feed.slug}),incident.feed) }}
        </div>
    </td>

    <td class="text-center">
        <small>
            {{ print.colordropbox('primary','calendar-alt',incident.updatedAt|date('Y-m-d'),'#',incident.updatedAt|date('Y-m-d')) }}
        </small>
    </td>
    {# <td class="text-center"> #}
    {# {{ print.colordropbox('primary','hashtag',incident.ltdCount,'#',incident.ltdCount) }} #}

    {# </td> #}
    <td class="text-center">
        {{ print.colordropbox(incident.reporter.color,incident.reporter.icon,incident.reporter,path('cert_unlp_ngen_user_detail_user',{'username': incident.reporter.username}),incident.reporter) }}
    </td>
</tr>

Resources/views/Incident/Frontend/list/stateLabel.html.twig
{# 
 This file is part of the Ngen - CSIRT Incident Report System.
 
 (c) CERT UNLP <support@cert.unlp.edu.ar>
 
 This source file is subject to the GPL v3.0 license that is bundled
 with this source code in the file LICENSE.
#}



{% if  incident.state.isAddressed %}
    {{ label_info(incident.state) }}
{% elseif incident.isLive %}
    {{ label_primary(incident.state) }}
{% else %}
    {{ label_danger(incident.state) }}
{% endif %}